#!/usr/bin/env bash
cd "$(dirname "$0")" || { echo "Can't chdir into $(dirname "$0")"; exit 1; }
[ ! -d "$(echo ~)" ] && { echo "Missing HOME dir: " ~; exit 1; }

# Create backup dir
rm -Rf ~/.dotfiles_backup ~/.bash_aliases
mkdir -p ~/.dotfiles_backup

# Install ~/.ssh/config on Darwin
if [ "$(uname)" == "Darwin" ]; then
  echo -n "$(echo ~)/.ssh/config - copying..."
  [ -f ~/.ssh/config ] && mv -f ~/.ssh/config ~/.dotfiles_backup && echo " [saved backup]" || echo
  mkdir -p ~/.ssh/control
  cp -f ~/.dotfiles/ssh_config_darwin ~/.ssh/dotfiles_ssh_config
fi

# Install ~/.ssh/config on Linux Desktop/Server
if [ "$XDG_CURRENT_DESKTOP" ] || [ "$GDMSESSION" ]; then
  echo -n "$(echo ~)/.ssh/config - copying..."
  [ -f ~/.ssh/config ] && mv -f ~/.ssh/config ~/.dotfiles_backup && echo " [saved backup]" || echo
  mkdir -p ~/.ssh/control
  cp -f ~/".dotfiles/ssh_config_linux_client" ~/.ssh/dotfiles_ssh_config
elif [[ "$(uname)" == "Linux" ]]; then
  echo -n "$(echo ~)/.ssh/config - copying..."
  [ -f ~/.ssh/config ] && mv -f ~/.ssh/config ~/.dotfiles_backup && echo " [saved backup]" || echo
  mkdir -p ~/.ssh
  cp -f ~/".dotfiles/ssh_config_linux_server" ~/.ssh/dotfiles_ssh_config
fi

# Remove previous dotfiles versions
grep '^# ~/.ssh/config for Darwin with stronger algorithms first' ~/.ssh/config && : > ~/.ssh/config
grep '^# ~/.ssh/config for Linux ' ~/.ssh/config && : > ~/.ssh/config

# add custom dotfiles_ssh_config
grep 'Include dotfiles_ssh_config' ~/.ssh/config >/dev/null || echo 'Include dotfiles_ssh_config' >> ~/.ssh/config

safe_copy() {
  echo -n "$(echo ~)/.$1 - copying..."
  [ -f ~/.$1 ] && mv -f ~/.$1 ~/.dotfiles_backup && echo " [saved backup]" || echo
  cp -f ~/.dotfiles/$1 ~/.$1
}

# Install dotfiles on ~
DOTFILES_SAFE=( zshrc bashrc bash_common gitconfig gitignore_global
                vimrc inputrc tmux.conf vimrc dir_colors screenrc)
for dotfile in "${DOTFILES_SAFE[@]}"; do
  safe_copy "$dotfile"
done

# Check if .bash_profile has no values
[ -f ~/.bash_apikeys ] && rm -f /.bash_apikeys
if [ -f ~/.bash_profile ]; then
  unset HOMEBREW_GITHUB_API_TOKEN GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL
  unset GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
  . ~/.bash_profile
  if [ ! "$HOMEBREW_GITHUB_API_TOKEN" ] && [ ! "$GIT_AUTHOR_NAME" ] && \
     [ ! "$GIT_AUTHOR_EMAIL" ] && [ ! "$GIT_COMMITTER_NAME" ] && \
     [ ! "$GIT_COMMITTER_EMAIL" ]; then
     safe_copy "bash_profile"
  fi
else
  safe_copy "bash_profile"
fi
echo

# Copy GIT_ variable values to .gitconfig on Desktops clients
if [[ "$(uname)" =~ Darwin ]] || [ "$XDG_CURRENT_DESKTOP" ] || [ "$GDMSESSION" ]; then
  [ -f ~/.bash_profile ] && . ~/.bash_profile
  # Detect NAME on git config
  if [ ! "$GIT_AUTHOR_NAME" ] || [ ! "$GIT_COMMITTER_NAME" ]; then
    echo -n "Enter your NAME  for git commits: " && read -r GIT_AUTHOR_NAME
    sed -i -e '/GIT_AUTHOR_NAME/d' -e '/GIT_COMMITTER_NAME/d' ~/.bash_profile
    echo "export GIT_AUTHOR_NAME='$GIT_AUTHOR_NAME'"       >> ~/.bash_profile
    echo "export GIT_COMMITTER_NAME='$GIT_AUTHOR_NAME'"    >> ~/.bash_profile
  fi
  # Detect EMAIL on git config
  if [ ! "$GIT_AUTHOR_EMAIL" ] || [ ! "$GIT_COMMITTER_EMAIL" ]; then
    echo -n "Enter your EMAIL for git commits: " && read -r GIT_AUTHOR_EMAIL
    sed -i -e '/GIT_AUTHOR_EMAIL/d' -e '/GIT_COMMITTER_EMAIL/d' ~/.bash_profile
    echo "export GIT_AUTHOR_EMAIL='$GIT_AUTHOR_EMAIL'"       >> ~/.bash_profile
    echo "export GIT_COMMITTER_EMAIL='$GIT_AUTHOR_EMAIL'"    >> ~/.bash_profile
  fi
  # Save NAME/EMAIL on git/bash_profile
  [ -f ~/.bash_profile ] && . ~/.bash_profile
  echo "Configuring git client on ~/.gitconfig and ~/.bash_profile with:"
  echo "  GIT_AUTHOR_NAME    ='$GIT_AUTHOR_NAME'"
  echo "  GIT_AUTHOR_EMAIL   ='$GIT_AUTHOR_EMAIL'"
  echo "  GIT_COMMITTER_NAME ='$GIT_COMMITTER_NAME'"
  echo "  GIT_COMMITTER_EMAIL='$GIT_COMMITTER_EMAIL'"
  [ "$GIT_AUTHOR_NAME" ]  && git config --global user.name  "$GIT_AUTHOR_NAME"
  [ "$GIT_AUTHOR_EMAIL" ] && git config --global user.email "$GIT_AUTHOR_EMAIL"
else
  # Remove custom git names on servers
  sed -i -e '/GIT_AUTHOR_EMAIL/d' -e '/GIT_COMMITTER_EMAIL/d' ~/.bash_profile
  sed -i -e '/GIT_AUTHOR_NAME/d'  -e '/GIT_COMMITTER_NAME/d'  ~/.bash_profile
  git config --global --remove-section user >/dev/null 2>&1
fi

# Remove push.default=simple for old git versions
if hash git >/dev/null 2>&1; then
  # git status . will return error on bad config (Eg. push.default=simple not supported)
  if ! git status . >/dev/null 2>&1; then
    git config --global --unset push.default
    git config --global --remove-section push
  fi
fi

if [ ! -f ~/.zprofile ] || ! grep -q '^GIT_' ~/.zprofile; then
  grep '^GIT_' ~/.bash_profile >> ~/.zprofile
fi

exit 0
