#!/usr/bin/env bash
[ ! "$HOME" ] && { echo "Missing \$HOME env variable"; exit 1; }

# Create backup dir
rm -Rf "$HOME/.dotfiles_backup"
mkdir -p "$HOME/.dotfiles_backup"

# Setup .ssh default
if [ "$(uname)" == "Darwin" ] && [ ! -f "$HOME/.ssh/config" ]; then
  echo "$HOME/.ssh/config - copying..."
  mkdir -p "$HOME/.ssh/control"
  cp -f "$HOME/.dotfiles/ssh_config" "$HOME/.ssh/config"
fi

safe_copy() {
  echo -n "$HOME/.$1 - copying..." 
  [ -f "$HOME/.$1" ] && mv -f "$HOME/.$1" "$HOME/.dotfiles_backup" && echo " [saved backup]" || echo
  cp -f "$HOME/.dotfiles/$1" "$HOME/.$1"
}
unsafe_copy() {
  [ -f "$HOME/.$1" ] && echo "$HOME/.$1 already exists - skipping file" && return 1
  echo -n "$HOME/.$1 - copying"
  cp -f "$HOME/.dotfiles/$1" "$HOME/.$1" && return 0
}

DOTFILES_SAFE=( bashrc bash_profile gitignore_global 
                inputrc tmux.conf vimrc dir_colors)
DOTFILES_UNSAFE=( bash_apikeys )

## Install
for dotfile in ${DOTFILES_SAFE[@]}; do
  safe_copy $dotfile
done
for dotfile in ${DOTFILES_UNSAFE[@]}; do
  unsafe_copy $dotfile
done
echo
echo "New dotfiles on $HOME/.dotfiles"
echo "Backup of your dotfiles on $HOME/.dotfiles_backup"
echo
echo "All done. Close and restart your terminal"
